#!/usr/bin/env python3
"""DLN Core–Variable Compression Simulation (combined-paper version)

This simulation is designed to test the *updated* thesis articulated in the review note:

Core (options) compression
  Network cognition is structurally more efficient because it represents shared
  option components once (F shared factors) rather than redundantly across each
  option branch (K options). This advantage exists in stable environments and
  does not require distribution shift or stakes variation.

Variable (stakes) compression
  Stakes/exposures are structured: many options share common risk drivers.
  The environment maintains a cumulative exposure state E_t and applies a
  quadratic exposure objective. The true incremental penalty includes cross-terms
  2 E_t b_i. A network agent that (i) learns factor-level exposure structure and
  (ii) tracks E_t can "hedge once" and avoid redundant hedging. A linear agent
  that treats each option's stakes independently and ignores E_t cross-terms
  cannot exploit this structure.

Core × Variable intersection (dual-purpose)
  Dual-purpose actions are those that are good on Core (high expected reward)
  and simultaneously good on Variable (reduce marginal exposure penalty given E_t).
  Linear agents optimize Core and Variable separately, missing intersection effects.

Learning cycle (mechanism)
  Network cognition is implemented as an explicit cycle:
    1) structural hypothesis (start with factor model),
    2) frequentist predictive check (rolling-window error),
    3) branch: exploit structure if correct OR expand/update hypothesis if wrong.

We intentionally keep the environment minimal (bandit-like) so the compression
mechanism is isolated and measurable.

Explicit modeling assumptions (mirrors the paper)
-------------------------------------------------
A1. Each option i exposes an observed core-factor label c_i in {0..F-1}.
    (This is the *shared component* representation.)
A2. Each option i exposes an observed stakes loading b_i.
A3. "Prior correct" condition: rewards are generated by a factor model mu_i = m_{c_i}+eps_i.
A4. "Prior wrong" condition: rewards are generated independently per option (c_i is irrelevant).
A5. Cognitive cost is a proxy (memory + compute scaling). It is not claimed as biological energy.

Outputs (paper-ready)
---------------------
- results/episode_metrics.csv        : per-seed episode metrics
- results/manifest.json              : run config + file manifest
- artifacts/tables/agg_summary.csv   : aggregated means/stds
- artifacts/figures/*.png            : figures used in the paper

Run
---
  python dln_core_variable_cycle.py --preset smoke --out ./dln_outputs
  python dln_core_variable_cycle.py --preset paper --out ./dln_outputs
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Literal

import numpy as np
import pandas as pd

Structure = Literal["structured", "unstructured"]


# -------------------------
# Environment
# -------------------------

@dataclass(frozen=True)
class EnvSpec:
    K: int
    F: int
    T: int
    stakes: float
    reward_sigma: float
    idio_mu_sigma: float
    idio_b_sigma: float
    factor_corr: float   # correlation between factor reward m_f and factor exposure g_f
    structure: Structure
    dual_purpose: bool


@dataclass
class EnvInstance:
    spec: EnvSpec
    c: np.ndarray        # (K,) core factor label
    mu: np.ndarray       # (K,) reward mean
    b: np.ndarray        # (K,) exposure loading
    dual_mask: np.ndarray  # (K,) dual-purpose flag (by construction)


def make_env(rng: np.random.Generator, spec: EnvSpec) -> EnvInstance:
    K, F = spec.K, spec.F

    # Factor assignment (observable shared component)
    c = rng.integers(0, F, size=K)

    # Factor-level Core and Variable parameters
    m = rng.normal(0.0, 1.0, size=F)
    m_std = (m - m.mean()) / (m.std() + 1e-9)

    z = rng.normal(0.0, 1.0, size=F)
    g = spec.factor_corr * m_std + math.sqrt(max(0.0, 1.0 - spec.factor_corr**2)) * z
    g = (g - g.mean()) / (g.std() + 1e-9)

    # Rewards
    if spec.structure == "structured":
        mu = m[c] + rng.normal(0.0, spec.idio_mu_sigma, size=K)
    else:
        # Prior-wrong for the factor hypothesis: independent option means
        mu = rng.normal(0.0, 1.0, size=K)

    mu = (mu - mu.mean()) / (mu.std() + 1e-9)

    # Stakes loadings with factor structure (Variable compression target)
    b = g[c] + rng.normal(0.0, spec.idio_b_sigma, size=K)
    b = (b - b.mean()) / (b.std() + 1e-9)

    # Dual-purpose construction: ensure at least one high-mu option has exposure opposite
    dual_mask = np.zeros(K, dtype=bool)
    if spec.dual_purpose and spec.stakes > 0:
        top = np.argsort(mu)[-max(5, K // 10):]
        # prefer a dual-purpose option in the top set: high mu and negative exposure
        cand = [i for i in top if b[i] < 0]
        if not cand:
            i0 = int(top[-1])
            b[i0] = -abs(b[i0])  # enforce hedge direction
            cand = [i0]
        dual_mask[cand] = True

    return EnvInstance(spec=spec, c=c, mu=mu, b=b, dual_mask=dual_mask)


def step_reward(rng: np.random.Generator, mu_i: float, sigma: float) -> float:
    return float(mu_i + rng.normal(0.0, sigma))


def step_penalty(E: float, b_i: float, stakes: float) -> float:
    # Quadratic exposure objective: stakes*((E+b)^2 - E^2) = stakes*(2Eb + b^2)
    return float(stakes * ((E + b_i) ** 2 - E ** 2))


# -------------------------
# Cognitive cost proxy
# -------------------------

@dataclass(frozen=True)
class CogCostWeights:
    mem: float = 0.01
    compute: float = 0.001
    switch: float = 25.0  # overhead when expanding to tabular


@dataclass
class CogCostCounter:
    mem_units: float = 0.0
    compute_units: float = 0.0
    switches: int = 0

    def total(self, w: CogCostWeights) -> float:
        return w.mem * self.mem_units + w.compute * self.compute_units + w.switch * self.switches


# -------------------------
# Agents
# -------------------------

class Agent:
    name: str

    def reset(self, env: EnvInstance, rng: np.random.Generator) -> None:
        raise NotImplementedError

    def act(self, t: int, env: EnvInstance) -> int:
        raise NotImplementedError

    def observe(self, a: int, r: float, pen: float, env: EnvInstance) -> None:
        raise NotImplementedError

    def cog_cost(self) -> float:
        raise NotImplementedError


class DotRandom(Agent):
    name = "Dot"

    def __init__(self, cost_w: CogCostWeights) -> None:
        self.cost_w = cost_w
        self.rng: np.random.Generator | None = None
        self.K = 0
        self.cost = CogCostCounter()

    def reset(self, env: EnvInstance, rng: np.random.Generator) -> None:
        self.rng = rng
        self.K = env.spec.K
        self.cost = CogCostCounter(mem_units=1.0, compute_units=0.0, switches=0)

    def act(self, t: int, env: EnvInstance) -> int:
        assert self.rng is not None
        self.cost.compute_units += 1.0
        return int(self.rng.integers(0, self.K))

    def observe(self, a: int, r: float, pen: float, env: EnvInstance) -> None:
        return

    def cog_cost(self) -> float:
        return self.cost.total(self.cost_w)


class LinearTabular(Agent):
    """Linear regime: item-by-item frequentist means; ignores E cross-term."""

    name = "Linear"

    def __init__(self, eps0: float, cost_w: CogCostWeights) -> None:
        self.eps0 = eps0
        self.cost_w = cost_w
        self.rng: np.random.Generator | None = None
        self.K = 0
        self.q: np.ndarray | None = None
        self.n: np.ndarray | None = None
        self.cost = CogCostCounter()

    def reset(self, env: EnvInstance, rng: np.random.Generator) -> None:
        self.rng = rng
        self.K = env.spec.K
        self.q = np.zeros(self.K, dtype=float)
        self.n = np.zeros(self.K, dtype=float)
        # memory scales with K
        self.cost = CogCostCounter(mem_units=2.0 * self.K, compute_units=0.0, switches=0)

    def _eps(self, t: int) -> float:
        return min(1.0, self.eps0 / math.sqrt(max(1, t)))

    def act(self, t: int, env: EnvInstance) -> int:
        assert self.rng is not None and self.q is not None and self.n is not None
        if self.rng.random() < self._eps(t):
            self.cost.compute_units += 1.0
            return int(self.rng.integers(0, self.K))

        # Variable heuristic ignores E cross-term: uses only local b^2
        score = self.q - env.spec.stakes * (env.b ** 2)
        self.cost.compute_units += float(self.K)
        return int(np.argmax(score))

    def observe(self, a: int, r: float, pen: float, env: EnvInstance) -> None:
        assert self.q is not None and self.n is not None
        self.n[a] += 1.0
        self.q[a] += (r - self.q[a]) / self.n[a]
        self.cost.compute_units += 5.0

    def cog_cost(self) -> float:
        return self.cost.total(self.cost_w)


class NetworkCycle(Agent):
    """Network regime with an explicit structural learning cycle.

    Hypotheses:
      - factor model: reward depends on factor f=c_i (compressed: O(F))
      - tabular model: reward depends on option i (expanded: O(K))

    Variable block:
      - learns factor-level exposure b_f (mean b within factor) online
      - tracks cumulative exposure E_t and uses the true marginal penalty

    Cycle:
      Every W steps, compare rolling MSE of factor vs tabular predictions.
      If tabular beats factor by a margin, expand/switch to tabular; otherwise
      exploit factor compression.

    Ablations:
      - Network-NoTest: disables the frequentist check (never evaluates mismatch)
      - Network-NoUpdate: runs the check but disallows switching (fixed prior)
    """

    def __init__(
        self,
        eps0: float,
        window: int,
        margin: float,
        allow_test: bool,
        allow_update: bool,
        cost_w: CogCostWeights,
        local_L: int = 5,
    ) -> None:
        self.eps0 = eps0
        self.window = window
        self.margin = margin
        self.allow_test = allow_test
        self.allow_update = allow_update
        self.cost_w = cost_w
        self.local_L = local_L

        if self.allow_test and self.allow_update:
            self.name = "Network-Full"
        elif (not self.allow_test) and self.allow_update:
            self.name = "Network-NoTest"
        elif self.allow_test and (not self.allow_update):
            self.name = "Network-NoUpdate"
        else:
            self.name = "Network-NoTestNoUpdate"

        self.rng: np.random.Generator | None = None
        self.K = 0
        self.F = 0

        # factor reward and exposure estimates
        self.m_hat: np.ndarray | None = None
        self.n_f: np.ndarray | None = None
        self.b_hat: np.ndarray | None = None
        self.n_b: np.ndarray | None = None

        # tabular reward estimates (allocated lazily)
        self.q: np.ndarray | None = None
        self.n: np.ndarray | None = None
        self.tabular_active: bool = False

        self.E: float = 0.0
        self.model: Literal["factor", "tabular"] = "factor"
        self.expansions: int = 0  # allocating tabular state
        self.revisions: int = 0   # switching between models

        self._err_factor: List[float] = []
        self._err_tab: List[float] = []

        self.cost = CogCostCounter()

    def reset(self, env: EnvInstance, rng: np.random.Generator) -> None:
        self.rng = rng
        self.K = env.spec.K
        self.F = env.spec.F

        self.m_hat = np.zeros(self.F, dtype=float)
        self.n_f = np.zeros(self.F, dtype=float)
        self.b_hat = np.zeros(self.F, dtype=float)
        self.n_b = np.zeros(self.F, dtype=float)

        self.q = None
        self.n = None
        self.tabular_active = False

        self.E = 0.0
        self.model = "factor"
        self.expansions = 0
        self.revisions = 0

        self._err_factor = []
        self._err_tab = []

        # memory scales with F (compressed)
        self.cost = CogCostCounter(mem_units=4.0 * self.F + 1.0, compute_units=0.0, switches=0)

    def _eps(self, t: int) -> float:
        return min(1.0, self.eps0 / math.sqrt(max(1, t)))

    def _maybe_allocate_tabular(self) -> None:
        if self.tabular_active:
            return
        self.q = np.zeros(self.K, dtype=float)
        self.n = np.zeros(self.K, dtype=float)
        self.tabular_active = True
        self.cost.mem_units += 2.0 * self.K
        self.cost.switches += 1
        self.expansions += 1  # track expansion separately

    def _maybe_switch(self, t: int) -> None:
        if not self.allow_test:
            return
        if t < self.window:
            return
        if len(self._err_factor) < self.window:
            return

        mse_factor = float(np.mean(self._err_factor[-self.window:]))
        mse_tab = float(np.mean(self._err_tab[-self.window:])) if len(self._err_tab) >= self.window else float("inf")
        if not self.tabular_active:
            mse_tab = float("inf")

        current_model = self.model
        if self.model == "factor" and mse_tab < (1.0 - self.margin) * mse_factor:
            if self.allow_update:
                self.model = "tabular"
        elif self.model == "tabular" and mse_factor < (1.0 - self.margin) * mse_tab:
            if self.allow_update:
                self.model = "factor"

        if self.model != current_model:
            self.revisions += 1  # track model switch

    def act(self, t: int, env: EnvInstance) -> int:
        assert self.rng is not None and self.m_hat is not None and self.b_hat is not None

        # exploration
        if self.rng.random() < self._eps(t):
            self.cost.compute_units += 1.0
            return int(self.rng.integers(0, self.K))

        stakes = env.spec.stakes

        if self.model == "factor":
            # factor scores incorporate Variable compression via b_hat and E
            # cost: scan F factors
            self.cost.compute_units += float(self.F)

            pen_f = stakes * (2.0 * self.E * self.b_hat + self.b_hat ** 2)
            score_f = self.m_hat - pen_f
            best_f = int(np.argmax(score_f))

            idx = np.where(env.c == best_f)[0]
            if idx.size == 0:
                self.cost.compute_units += 1.0
                return int(self.rng.integers(0, self.K))

            # local search within factor (bounded, does not scale with K)
            # Smart search: when hedging matters (stakes > 0 and |E| > threshold),
            # prioritize candidates by exposure direction rather than random sampling.
            # This reflects Network's structural understanding: "I know what I'm looking for."
            L = min(self.local_L, idx.size)

            if stakes > 0 and abs(self.E) > 0.5:
                # Directed search based on exposure state
                # E > 0: prefer low b (negative exposure = hedge)
                # E < 0: prefer high b (positive exposure = rebalance toward zero)
                sorted_idx = idx[np.argsort(env.b[idx])]  # ascending by b
                if self.E > 0:
                    cand = sorted_idx[:L]  # lowest b values (hedges)
                else:
                    cand = sorted_idx[-L:]  # highest b values (rebalance)
            else:
                # Random sampling when hedging doesn't matter
                cand = self.rng.choice(idx, size=L, replace=False)

            pen_inc = stakes * (2.0 * self.E * env.b[cand] + env.b[cand] ** 2)
            util_pred = self.m_hat[best_f] - pen_inc
            self.cost.compute_units += float(L)
            return int(cand[int(np.argmax(util_pred))])

        # tabular model (expanded)
        self._maybe_allocate_tabular()
        assert self.q is not None
        self.cost.compute_units += float(self.K)

        pen_inc = stakes * (2.0 * self.E * env.b + env.b ** 2)
        score = self.q - pen_inc
        return int(np.argmax(score))

    def observe(self, a: int, r: float, pen: float, env: EnvInstance) -> None:
        assert self.m_hat is not None and self.n_f is not None and self.b_hat is not None and self.n_b is not None

        # Update exposure state
        self.E += float(env.b[a])

        # Update factor reward estimate
        f = int(env.c[a])
        self.n_f[f] += 1.0
        self.m_hat[f] += (r - self.m_hat[f]) / self.n_f[f]

        # Update factor exposure estimate (b is observed)
        self.n_b[f] += 1.0
        self.b_hat[f] += (float(env.b[a]) - self.b_hat[f]) / self.n_b[f]

        # Update tabular reward estimate if expanded
        if self.tabular_active:
            assert self.q is not None and self.n is not None
            self.n[a] += 1.0
            self.q[a] += (r - self.q[a]) / self.n[a]

        # Rolling errors for the explicit predictive check
        pred_f = float(self.m_hat[f])
        self._err_factor.append((r - pred_f) ** 2)

        if self.tabular_active:
            pred_t = float(self.q[a])
            self._err_tab.append((r - pred_t) ** 2)
        else:
            self._err_tab.append(float("inf"))

        # If factor predictor keeps failing, allocate tabular so we can compare.
        if self.allow_test and (not self.tabular_active) and len(self._err_factor) >= self.window:
            mse_f = float(np.mean(self._err_factor[-self.window:]))
            if mse_f > 1.5:
                self._maybe_allocate_tabular()

        self._maybe_switch(len(self._err_factor))
        self.cost.compute_units += 10.0

    def cog_cost(self) -> float:
        return self.cost.total(self.cost_w)


# -------------------------
# Experiment runner
# -------------------------

@dataclass(frozen=True)
class RunSpec:
    preset: Literal["smoke", "paper", "boundary-kf", "stakes-sweep"]
    seeds: int
    K_values: List[int]
    F: int
    T: int
    stakes_values: List[float]
    structures: List[Structure]
    dual_purpose: bool
    eps0: float
    window: int
    margin: float
    reward_sigma: float
    idio_mu_sigma: float
    idio_b_sigma: float
    factor_corr: float
    cog_lambda: float
    cost_w: CogCostWeights


def preset_config(preset: str) -> RunSpec:
    if preset == "smoke":
        return RunSpec(
            preset="smoke",
            seeds=15,
            K_values=[20, 50],
            F=5,
            T=60,
            stakes_values=[0.0, 1.0],
            structures=["structured", "unstructured"],
            dual_purpose=True,
            eps0=0.4,
            window=20,
            margin=0.1,
            reward_sigma=0.25,
            idio_mu_sigma=0.05,
            idio_b_sigma=0.05,
            factor_corr=0.35,
            cog_lambda=1.0,
            cost_w=CogCostWeights(mem=0.01, compute=0.001, switch=25.0),
        )
    if preset == "paper":
        return RunSpec(
            preset="paper",
            seeds=100,
            K_values=[20, 50, 100, 200],
            F=5,
            T=80,
            stakes_values=[0.0, 1.0],
            structures=["structured", "unstructured"],
            dual_purpose=True,
            eps0=0.4,
            window=20,
            margin=0.1,
            reward_sigma=0.25,
            idio_mu_sigma=0.05,
            idio_b_sigma=0.05,
            factor_corr=0.35,
            cog_lambda=1.0,
            cost_w=CogCostWeights(mem=0.01, compute=0.001, switch=25.0),
        )
    # -------------------------------------------------------------------------
    # BOUNDARY CONDITION PRESETS (for reviewer response)
    # -------------------------------------------------------------------------
    if preset == "boundary-kf":
        # Test K=F boundary condition where compression advantage should vanish
        # At K=F, Network has no advantage (nothing to compress)
        return RunSpec(
            preset="boundary-kf",
            seeds=50,
            K_values=[5, 10, 20, 50],  # K=5=F is the critical boundary
            F=5,
            T=80,
            stakes_values=[0.0, 1.0],
            structures=["structured", "unstructured"],
            dual_purpose=True,
            eps0=0.4,
            window=20,
            margin=0.1,
            reward_sigma=0.25,
            idio_mu_sigma=0.05,
            idio_b_sigma=0.05,
            factor_corr=0.35,
            cog_lambda=1.0,
            cost_w=CogCostWeights(mem=0.01, compute=0.001, switch=25.0),
        )
    if preset == "stakes-sweep":
        # Test intermediate stakes values (reviewer point: only tested 0 and 1)
        return RunSpec(
            preset="stakes-sweep",
            seeds=50,
            K_values=[50, 200],  # Two representative K values
            F=5,
            T=80,
            stakes_values=[0.0, 0.25, 0.5, 0.75, 1.0],  # Full sweep
            structures=["structured"],  # Focus on structured for stakes effect
            dual_purpose=True,
            eps0=0.4,
            window=20,
            margin=0.1,
            reward_sigma=0.25,
            idio_mu_sigma=0.05,
            idio_b_sigma=0.05,
            factor_corr=0.35,
            cog_lambda=1.0,
            cost_w=CogCostWeights(mem=0.01, compute=0.001, switch=25.0),
        )
    raise ValueError(f"Unknown preset: {preset}")


def run_episode(env: EnvInstance, agent: Agent, rng: np.random.Generator) -> Dict[str, float]:
    agent.reset(env, rng)
    E = 0.0
    total_r = 0.0
    total_pen = 0.0
    dual_picks = 0
    dual_picks_cond = 0  # conditional: only when |E| >= 0.5
    dual_cond_steps = 0   # steps where |E| >= 0.5
    E_abs_sum = 0.0

    for t in range(1, env.spec.T + 1):
        a = agent.act(t, env)
        r = step_reward(rng, env.mu[a], env.spec.reward_sigma)
        pen = step_penalty(E, env.b[a], env.spec.stakes)

        # Track conditional dual picks (when hedging matters)
        if abs(E) >= 0.5:
            dual_cond_steps += 1
            if env.dual_mask[a]:
                dual_picks_cond += 1

        E += float(env.b[a])
        E_abs_sum += abs(E)

        total_r += r
        total_pen += pen
        if env.dual_mask[a]:
            dual_picks += 1

        agent.observe(a, r, pen, env)

    util = total_r - total_pen
    cog = agent.cog_cost()

    # Get expansion/revision counts from Network agents
    expansions = float(getattr(agent, "expansions", 0))
    revisions = float(getattr(agent, "revisions", 0))

    return dict(
        total_reward=total_r,
        total_penalty=total_pen,
        utility=util,
        cognitive_cost=cog,
        dual_picks=float(dual_picks),
        dual_picks_cond=float(dual_picks_cond),
        dual_cond_steps=float(dual_cond_steps),
        E_abs_mean=E_abs_sum / float(env.spec.T),
        expansions=expansions,
        revisions=revisions,
    )


def run_suite(cfg: RunSpec, out_dir: str) -> pd.DataFrame:
    out = Path(out_dir)
    results_dir = out / "results"
    artifacts_dir = out / "artifacts"
    (artifacts_dir / "tables").mkdir(parents=True, exist_ok=True)
    (artifacts_dir / "figures").mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)

    rows: List[Dict[str, object]] = []

    for seed in range(cfg.seeds):
        rng = np.random.default_rng(seed)
        for K in cfg.K_values:
            for stakes in cfg.stakes_values:
                for structure in cfg.structures:
                    spec = EnvSpec(
                        K=K,
                        F=cfg.F,
                        T=cfg.T,
                        stakes=stakes,
                        reward_sigma=cfg.reward_sigma,
                        idio_mu_sigma=cfg.idio_mu_sigma,
                        idio_b_sigma=cfg.idio_b_sigma,
                        factor_corr=cfg.factor_corr,
                        structure=structure,
                        dual_purpose=cfg.dual_purpose,
                    )
                    env = make_env(rng, spec)

                    agents: List[Agent] = [
                        DotRandom(cfg.cost_w),
                        LinearTabular(cfg.eps0, cfg.cost_w),
                        NetworkCycle(cfg.eps0, cfg.window, cfg.margin, True, True, cfg.cost_w),
                        NetworkCycle(cfg.eps0, cfg.window, cfg.margin, False, True, cfg.cost_w),
                        NetworkCycle(cfg.eps0, cfg.window, cfg.margin, True, False, cfg.cost_w),
                    ]

                    for agent in agents:
                        ep = run_episode(env, agent, rng)
                        cau = float(ep["utility"]) - cfg.cog_lambda * float(ep["cognitive_cost"])
                        # Compute conditional dual rate (only when hedging matters: |E| >= 0.5)
                        dual_rate = float(ep["dual_picks"]) / float(cfg.T)
                        dual_cond_steps = float(ep["dual_cond_steps"])
                        dual_rate_cond = float(ep["dual_picks_cond"]) / max(1.0, dual_cond_steps)
                        rows.append(
                            dict(
                                seed=seed,
                                agent=agent.name,
                                K=K,
                                F=cfg.F,
                                T=cfg.T,
                                stakes=stakes,
                                structure=structure,
                                total_reward=float(ep["total_reward"]),
                                total_penalty=float(ep["total_penalty"]),
                                utility=float(ep["utility"]),
                                cognitive_cost=float(ep["cognitive_cost"]),
                                cost_adjusted_utility=float(cau),
                                dual_picks=float(ep["dual_picks"]),
                                dual_rate=dual_rate,
                                dual_rate_cond=dual_rate_cond,
                                E_abs_mean=float(ep["E_abs_mean"]),
                                expansions=float(ep["expansions"]),
                                revisions=float(ep["revisions"]),
                            )
                        )

    df = pd.DataFrame(rows)
    df_path = results_dir / "episode_metrics.csv"
    df.to_csv(df_path, index=False)

    # Aggregation
    agg = (
        df.groupby(["agent", "structure", "stakes", "K"], as_index=False)
        .agg(
            reward_mean=("total_reward", "mean"),
            reward_std=("total_reward", "std"),
            penalty_mean=("total_penalty", "mean"),
            penalty_std=("total_penalty", "std"),
            utility_mean=("utility", "mean"),
            utility_std=("utility", "std"),
            cog_mean=("cognitive_cost", "mean"),
            cog_std=("cognitive_cost", "std"),
            cau_mean=("cost_adjusted_utility", "mean"),
            cau_std=("cost_adjusted_utility", "std"),
            dual_mean=("dual_picks", "mean"),
            dual_rate_mean=("dual_rate", "mean"),
            dual_rate_std=("dual_rate", "std"),
            dual_rate_cond_mean=("dual_rate_cond", "mean"),
            dual_rate_cond_std=("dual_rate_cond", "std"),
            E_abs_mean=("E_abs_mean", "mean"),
            expansions_mean=("expansions", "mean"),
            revisions_mean=("revisions", "mean"),
        )
    )
    table_path = artifacts_dir / "tables" / "agg_summary.csv"
    agg.to_csv(table_path, index=False)

    # Figures
    import matplotlib.pyplot as plt

    # Fig 1: stable structured env, cost-adjusted utility vs K
    for stakes in [0.0, 1.0]:
        plt.figure()
        sub = agg[(agg["structure"] == "structured") & (agg["stakes"] == stakes)]
        for agent in ["Dot", "Linear", "Network-Full", "Network-NoTest", "Network-NoUpdate"]:
            s = sub[sub["agent"] == agent].sort_values("K")
            if len(s) == 0:
                continue
            plt.errorbar(s["K"], s["cau_mean"], yerr=s["cau_std"], marker="o", label=agent)
        plt.xlabel("Number of options K")
        plt.ylabel("Cost-adjusted utility (mean ± sd)")
        plt.title(f"Stable environment (structured), stakes={stakes}")
        plt.legend()
        plt.tight_layout()
        plt.savefig(artifacts_dir / "figures" / f"fig_cau_vs_K_structured_stakes{stakes}.png", dpi=200)
        plt.close()

    # Fig 2: CONDITIONAL dual-purpose pick rate (when hedging matters: |E| >= 0.5)
    plt.figure()
    sub = agg[(agg["structure"] == "structured") & (agg["stakes"] == 1.0)]
    for agent in ["Linear", "Network-Full", "Network-NoTest", "Network-NoUpdate"]:
        s = sub[sub["agent"] == agent].sort_values("K")
        if len(s) == 0:
            continue
        plt.errorbar(s["K"], s["dual_rate_cond_mean"], yerr=s["dual_rate_cond_std"], marker="o", label=agent, capsize=3)
    plt.xlabel("Number of options K")
    plt.ylabel("Conditional dual-purpose pick rate")
    plt.title("Dual-purpose discovery when hedging matters (|E| ≥ 0.5)")
    plt.legend()
    plt.tight_layout()
    plt.savefig(artifacts_dir / "figures" / "fig_dual_purpose_rate.png", dpi=200)
    plt.close()

    # Fig 3: cycle response in unstructured, stakes=0 (prior-wrong) - show expansions
    plt.figure()
    sub = agg[(agg["structure"] == "unstructured") & (agg["stakes"] == 0.0)]
    for agent in ["Network-Full", "Network-NoTest", "Network-NoUpdate"]:
        s = sub[sub["agent"] == agent].sort_values("K")
        if len(s) == 0:
            continue
        plt.plot(s["K"], s["expansions_mean"], marker="o", label=agent)
    plt.xlabel("Number of options K")
    plt.ylabel("Mean hypothesis expansions")
    plt.title("Prior-wrong condition (unstructured): cycle response")
    plt.legend()
    plt.tight_layout()
    plt.savefig(artifacts_dir / "figures" / "fig_switches.png", dpi=200)
    plt.close()

    manifest = dict(
        preset=cfg.preset,
        seeds=cfg.seeds,
        K_values=cfg.K_values,
        F=cfg.F,
        T=cfg.T,
        stakes_values=cfg.stakes_values,
        structures=cfg.structures,
        dual_purpose=cfg.dual_purpose,
        eps0=cfg.eps0,
        window=cfg.window,
        margin=cfg.margin,
        reward_sigma=cfg.reward_sigma,
        idio_mu_sigma=cfg.idio_mu_sigma,
        idio_b_sigma=cfg.idio_b_sigma,
        factor_corr=cfg.factor_corr,
        cog_lambda=cfg.cog_lambda,
        cost_weights=dataclasses.asdict(cfg.cost_w),
        outputs=dict(
            episode_metrics=str(df_path),
            agg_summary=str(table_path),
            figures_dir=str(artifacts_dir / "figures"),
        ),
    )
    (results_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))

    return df


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--preset", choices=["smoke", "paper", "boundary-kf", "stakes-sweep"], default="paper")
    ap.add_argument("--out", default="./dln_outputs")
    args = ap.parse_args()

    cfg = preset_config(args.preset)
    run_suite(cfg, args.out)

    print("DLN simulation complete.")
    print(f"Outputs written to: {args.out}")


if __name__ == "__main__":
    main()
